# Workflow for building and deploying a Hugo site
name: Deploy Hugo site

on:
  # Runs on pushes targeting the default branch
  push:
    branches: 
      - staging
#      - main
#  pull_request:
#    types:
#      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

## Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
## However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: stage-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  info:
    runs-on: ubuntu-latest
    outputs:
      version_id: ${{ steps.set_outputs.outputs.version_id }}
    steps:
      - name: Set version_id
        run: |
          version_id=$(date "+%Y%m%d%H%M%S")
          echo "version_id=$version_id"
          echo "version_id=$version_id" >> $GITHUB_OUTPUT
      - name: Echo settings
        run: |
          echo "github.workflow: ${{ github.workflow }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.head_ref: ${{ github.head_ref }}"

  # Build job
  build:
    runs-on: ubuntu-latest
    if: github.ref_name == 'staging'
    environment: staging
    needs: info
    env:
      HUGO_VERSION: 0.138.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Upload files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_KEY }}
          source: "./public"
          target: "sources/${{ needs.info.outputs.version_id }}"
      - name: Create releaase tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: stage/${{ needs.info.outputs.version_id }}
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ env.RELEASE_TAG }}
          name: Release for staging ${{ env.RELEASE_TAG }}
          version: ${{ env.RELEASE_TAG }}
          publish: true

  # Deployment job for staging
  staging_deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == 'staging'
    environment: staging
    needs: [info, build]
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_KEY }}
          known_hosts: ${{ secret.KNOWN_HOSTS }}
          if_key_exists: fail
      - name: Deploy staging site
        run: ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} './deploy_stage.sh ${{ needs.info.outputs.version_id }}'


  # Deployment job for production
  production_deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    environment: production
    needs: info
    steps:
      - name: Deploy production site
        run: |
          echo "Deploy production site"
